name: Build and Deploy to Hostinger
on:
 push:
  branches:
   - main # or the name of your default branch

jobs:
 build_and_deploy:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout
     uses: actions/checkout@v2.3.2

   - name: Install and Build
     run: |
      npm install
      npm run build

   - name: Deploy to Hostinger
     uses: SamKirkland/FTP-Deploy-Action@4.0.0
     with:
      server: adidecodes.me
      username: u295552106.adidecodes.me
      password: ${{ secrets.FTP_PASSWORD }}
      server-dir: /
      local-dir: dist/
